### ISSUE TITLE
some mechs are not importing correctly

### ISSUE THREAD

**Issue by makenzie71** [Markemp/Cryengine-Importer#16]
Some of the mechs I've recently imported did not come with all the same movement armatures (if that's the right word).  They usually have boxes that allow me to grab the appropriate appendage and move it, and all the other parts that have to move with it do so.  Things like rotation are not available...so I can't twist at the waste.  The three mechs that have given me this issue are the rifleman, raven, and flea.  I thought I was simply missing a step but I went through the conversion and import process with the nightstar and it imported properly.  I went and deleted all of the data for the flea/raven/rifleman and tried it again and those three models are still bugged.

This is a screenshot of how they import and an error that pops up

https://imgur.com/a/06THeoN

**Comment by Markemp** [comment]
@makenzie71 Can you pull the latest zip file and verify that it is working?  The posing is a bit wonky on some of the mechs due to weird constraint issues, but you should still be able to set them up for printing.
