### ISSUE TITLE
Mechs coming out incompletely rigged

### ISSUE THREAD

**Issue by MagusMachinae** [Markemp/Cryengine-Importer#18]
As the title suggests, certain mechs, like the Roughneck and Cataphract are only half-rigged when imported, whereas others like the Dragon and Stalker don't have any control bones at all. Using the latest release on blender 2.91
<img width="671" alt="blender_9n0Zr0HkR1" src="https://user-images.githubusercontent.com/47104486/140662032-1b32d58e-bfcd-449f-9b3a-334dcff9ec0f.png">
![blender_aBcB0U1Lkq](https://user-images.githubusercontent.com/47104486/140662038-ed4be280-2762-490e-bbc3-927b33e76f3e.jpg)
![blender_VB0n3YLtjq](https://user-images.githubusercontent.com/47104486/140662040-2f42361c-679b-4f40-bd31-cab8b61c0a28.jpg)

**Comment by Markemp** [comment]
Can you reinstall the latest version of the importer and try again?  All the mechs listed above seem to be working correctly with v1.0.8.

![image](https://user-images.githubusercontent.com/12057128/141129255-c21463cd-e7ed-422c-87ca-31552c5fa954.png)

**Comment by MagusMachinae** [comment]
I did give reinstalling a go a few times.

I notice that your screenshot also does not have the control boxes for the feet of the RGH, is that to do with the model itself?

**Comment by Markemp** [comment]
The bones are there, but it looks like the widget didn't draw properly.  I'll check into that.  But you can click on the bones in the outliner and move the legs that way.

![image](https://user-images.githubusercontent.com/12057128/141133262-355eb8fd-0497-49bf-8f86-a175ced5cfad.png)

**Comment by Markemp** [comment]
Just made a new release for Blender 3.0 and newer that fixes this issue.  
https://github.com/Markemp/Cryengine-Importer/releases/tag/v2.1.0

This version should only work for Blender 3.0+.  For Blender 2.93, you can still use the 2.0.8 version, although this problem will probably still be there.

![image](https://user-images.githubusercontent.com/12057128/167318985-4b3f4269-def6-4fdc-9705-ea516c9ca7a4.png)

**Comment by Markemp** [comment]
Still some issues with the Dragon mech.  Working through those now.

**Comment by Markemp** [comment]
Dragon is working decently with version 2.1.1.  There is no left hand bone, so it's using the target bone, which is really close to the elbow and is finicky to position.  Atlas is still a mess because of tons of non-standard armature issues, so some manual cleanup will still be required.
