### ISSUE TITLE
Unable to enable plugin inside Blender 3.0 

### ISSUE THREAD

**Issue by gaddenar** [Markemp/Cryengine-Importer#19]
Downloaded the latest release of the plugin and tried to enable it in Blender 3.0.
When enabling it I get several errors.
![image](https://user-images.githubusercontent.com/5212045/147891059-1c70a218-607b-4870-a1e1-ff93a0034e89.png)

Am I missing something?

**Comment by Markemp** [comment]
Looks like I have to update the project to support Blender 3.0.  Thanks for the heads up.  I'll try to get to it in the next couple of weeks, but if you need it sooner you might want to install the latest 2.93 version.

**Comment by Markemp** [comment]
Released a new version to support Blender 3.0 and newer.
