### ISSUE TITLE
cannot import mechs

### ISSUE THREAD

**Issue by DropDownWidget** [Markemp/Cryengine-Importer#23]
This may have been solved before but whenever I try to import a mech this error message pops up
![Screenshot (705)](https://github.com/Markemp/Cryengine-Importer/assets/152328068/f6ac6a8c-6cbd-4bbd-b5b0-60c195459772)
I'm using blender 2.93.5 however I've tried using older versions (2.80 & 2.79) and they have the same issue. To my knowledge I have the most recent version of this addon   
![Screenshot (707)](https://github.com/Markemp/Cryengine-Importer/assets/152328068/0137b768-0e82-4a4c-a08a-06c9dd3f0091)
this is the command I used to convert the assets 
![Screenshot (699)](https://github.com/Markemp/Cryengine-Importer/assets/152328068/4f7dc7a9-cb98-422b-aa67-0bd3f02a9ea3)
I'm very sorry for the inconvenience but I've run out of ideas for trouble shooting this myself.

**Comment by Markemp** [comment]
It shouldn't require elevated permissions (admin) to run, unless the folder itself requires admin access.  Did you extract all the game files to `c:/export/files`?  There should be an `Objects` and `Textures` directory in there if so, among others.

I also haven't tested it with 4.0 yet.  It should work with 3.6 still, but will need to do some testing/updates to get it to work with 4.

**Comment by Markemp** [comment]
Looks like the armature didn't import properly.  I tested on Blender 4.0.2 and got the same thing, so I def need to fix the importer for the new version.  I tried on 3.6, and it worked properly (except the layers stuff is still broken). This is what it should look like:

![image](https://github.com/Markemp/Cryengine-Importer/assets/12057128/6f11543b-77d7-478e-b0c9-017f8b000772)

The extra spiky things are empty nodes, which are nodes in the game files that represent things like points for add-ons or animations, like where a muzzle flash should come from.  They are normal, but should be moved to a separate layer once I get that fixed up.

Try the import again on 3.6.  It should look like above. Let me know if it doesn't though.

**Comment by Markemp** [comment]
Released a new version that supports Blender 4.0.  Also removed the Asset Importer since aside from creating better materials, it really didn't have much of a use.  The prefab importer is still working though.

Annoying side effect of Blender 4.0 is that in the Principled BSDF node, they set the metallic setting to 0.  This needs to be changed to a higher value (1.0 for example) for the materials to show the textures.
