### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by softyoda** [Markemp/Cryengine-Importer#3]
Hello, i did not see any update of Cryengine-Importer addon. Did it still work ? Is it possible to get models from star citizens ? I would like to make a blender animation using star citizens assets, but i don't really know how to do that.
I tried to send you an email to nfo@heffaypresents.com but the server rejected my email (maby yout adress is offline)

**Comment by Markemp** [comment]
It is still being supported and updated.  The Importer is more designed for classic CryEngine games, and it won't work against CE games that use binary XML files like SC.  

The extraction tool for SC is managed by some other group, and I don't know what the status of that is with respect to 3.3.  

But if you want to import assets into Blender, then you want to use the Cryengine-Converter project.  This one is only for taking the Collada assets that were converted with that into Blender.  They have to be converted first.

**Comment by Markemp** [comment]
Closing this issue as there is no project work related to it.
