### ISSUE TITLE
Can't open 80000800 files

### ISSUE THREAD

**Issue by LapisLazulis** [Markemp/Cryengine-Importer#6]
Hello, been wanting to test your CryEngine importer, however when converting with your Converter, it gives me this error:

`There was an error rendering H:\boom\test.chr

Version 80000800 of ChunkCompiledBones is not supported

   à CgfConverter.CryEngine_Core.Chunk.New[T](UInt32 version) dans C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Chunks\Chunk.cs:ligne 0
   à CgfConverter.CryEngine_Core.Model.Read_Chunks(BinaryReader reader) dans C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Model.cs:ligne 292
   à CgfConverter.CryEngine_Core.Model.Load(String fileName) dans C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Model.cs:ligne 180
   à CgfConverter.CryEngine..ctor(String fileName, String dataDir) dans C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine\CryEngine.cs:ligne 59
   à CgfConverterConsole.Program.Main(String[] args)
********************************************************************************
`

Same happen with a material
`********************************************************************************
There was an error rendering H:\boom\test.cgf

Version 80000800 of ChunkMtlName is not supported

   à CgfConverter.CryEngine_Core.Chunk.New[T](UInt32 version) dans C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Chunks\Chunk.cs:ligne 0
   à CgfConverter.CryEngine_Core.Model.Read_Chunks(BinaryReader reader) dans C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Model.cs:ligne 292
   à CgfConverter.CryEngine_Core.Model.Load(String fileName) dans C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine_Core\Model.cs:ligne 180
   à CgfConverter.CryEngine..ctor(String fileName, String dataDir) dans C:\Users\Geoff\Source\Repos\cgf-converter\CgfConverter\CryEngine\CryEngine.cs:ligne 59
   à CgfConverterConsole.Program.Main(String[] args)
********************************************************************************`

Any idea about how to fix it? I can upload the file if you want

**Comment by MiracleBlessing** [comment]
Pretty sure this was meant for the CgfConverter, not Importer. The latter is used to import the assets converted by the former.

**Comment by LapisLazulis** [comment]
> Pretty sure this was meant for the CgfConverter, not Importer. The latter is used to import the assets converted by the former.

Not going to lie, I've put this here because there's been 6 months old issues without any anwser, so since some more recent there were anwsered, thought I'd have more luck doing it here :/

**Comment by Markemp** [comment]
Which game is this for?  It looks like you are using some partial files in the H:\boom directory, but cgf-converter really requires the full game file structure to be present.  A lot of .cgf files reference other files by relative path, so if things aren't where they are expected, it will often fail.

I'm finishing up some updates for the importer here, and then will take a look at the converter to fix some outstanding issues as time permits.

**Comment by LapisLazulis** [comment]
> Which game is this for? It looks like you are using some partial files in the H:\boom directory, but cgf-converter really requires the full game file structure to be present. A lot of .cgf files reference other files by relative path, so if things aren't where they are expected, it will often fail.
> 
> I'm finishing up some updates for the importer here, and then will take a look at the converter to fix some outstanding issues as time permits.

I tried doing it in the game folder too but sadly it's not working, the game is Sonic Boom: Rise of Lyric for the WiiU!

**Comment by Markemp** [comment]
Wow, I had no idea they made Cryengine games for the WiiU.  I'll see if I can find some files to test on.

**Comment by LapisLazulis** [comment]
> Wow, I had no idea they made Cryengine games for the WiiU. I'll see if I can find some files to test on.

Yeah the game had a very troubled development and it started on PS4/One but shifted to WiiU due to contracts problem, and they had to seek help from Nintendo and Crytek to get it to work on WiiU, result is a poor-coded game :p

**Comment by Markemp** [comment]
I'm not sure how I can legally get access to these game files.  I'll see if I can figure out the issue from the error above, but this might be a bit out of scope.

**Comment by LapisLazulis** [comment]
Sure no problem, it's not the most important thing ever anyway! :)

**Comment by Markemp** [comment]
Sonic Boom is now supported in cryengine converter, which is what this Issue seems related to.  Closing.
